<?php


//adding text box and button in site information
function axlerant_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
 
  $form['siteapikeys'] = array(
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#default_value' => (variable_get('siteapikey') ? variable_get('siteapikey') : 'No API Key yet'),
    );
 
	$form['submit']=array(
	'#type'=>'submit', 
	'#value'=>(variable_get('siteapikey') !='No API Key yet' ? 'Update configuration' : 'Save API configuration')
	
	);
 $form['#submit'][] = 'site_submit';
      }
	  
	  
}
function site_submit($form, &$form_state) {

	if (!empty( $form_state['values']['siteapikeys'] )) {

    variable_set('siteapikey', $form_state['values']['siteapikeys']);
  drupal_set_message(t('The Site API Key  %a', array('%a' => variable_get('siteapikey'))));
  }
  else{
    variable_set('siteapikey', 'No API Key yet');
  }
}
//-----------------------------------------------------------
//creating hook menu to get json data  
function axlerant_menu() {


 $items['node/%node/json'] = array(
    'title' => 'JSON data',
    'page callback' => 'myjsondata',
    'page arguments' => array(1),
    'access callback' => 'myjsondata_permission',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    
  );

  $items['page_json/%/%'] = array(
  'title' => 'Json Representation of Node',
  'page callback' => 'myjson_representation',
    'access callback' => TRUE,
    'page arguments' => array(1, 2),
  );
  return $items;
}


//Permission only for Basic page
function myjsondata_permission($node) {
  
  if ($node->type != 'page') {
    return FALSE;
  }
  return TRUE;
}

function myjsondata($node) {
  $site_api = variable_get('siteapikey');
  $nid_node = $node->nid;
 $url = $_GET['q'];
  
  $pa = explode("/", $url); 
  $url1 = "page_json/" . $site_api . "/" . $pa[1];
  drupal_goto($url1);
}


function myjson_representation($sitesapi, $nid) {
  $node = node_load($nid);
if(variable_get('siteapikey')!='No API Key yet' && $node->nid && $sitesapi == variable_get('siteapikey') && $node->type == 'page' ) {
   drupal_json_output( $node );
}
else {
  echo "Access Denied";
}  

}








?>